from flask import Blueprint, render_template, abort

product_bp = Blueprint('product', __name__)

@product_bp.route('/product/<int:product_id>')
def product_detail(product_id):
    # Sample product data - matching actual available images
    products = {
        1: {"id": 1, "name": "Monstera Deliciosa", "price": 25.99, "category": "indoor", "image": "indoor/monstera.jpg", "rating": 5, "description": "The Monstera Deliciosa, also known as the Swiss Cheese Plant, is a stunning tropical houseplant famous for its unique split leaves. This Instagram-worthy plant develops beautiful fenestrations (holes) as it matures, creating an exotic and dramatic appearance that makes it a perfect statement piece for any modern home.", "is_popular": True},
        2: {"id": 2, "name": "Snake Plant", "price": 19.99, "category": "indoor", "image": "indoor/snake-plant.jpg", "rating": 5, "description": "The Snake Plant (Sansevieria) is the ultimate low-maintenance houseplant, perfect for beginners or busy plant parents. With its striking upright leaves featuring beautiful yellow edges, this hardy succulent is nearly indestructible and excellent for improving indoor air quality while requiring minimal care.", "is_popular": True},
        3: {"id": 3, "name": "Peace Lily", "price": 20.00, "category": "indoor", "image": "indoor/peace-lily.jpg", "rating": 4, "description": "The elegant Peace Lily is a graceful flowering houseplant that produces beautiful white blooms throughout the year. Known for its air-purifying qualities and ability to thrive in low-light conditions, this plant signals when it needs water by gently drooping its leaves."},
        4: {"id": 4, "name": "Golden Pothos", "price": 18.00, "category": "indoor", "image": "indoor/golden_potho.jpg", "rating": 4, "description": "The Golden Pothos is a versatile trailing vine with heart-shaped leaves variegated in golden yellow. This fast-growing, forgiving plant is perfect for hanging baskets, shelves, or climbing up moss poles, making it ideal for adding natural beauty to any space."},
        5: {"id": 5, "name": "Fiddle Leaf Fig", "price": 35.00, "category": "indoor", "image": "indoor/fiddle-leaf-fig.jpg", "rating": 4, "description": "The Fiddle Leaf Fig is a dramatic statement plant with large, violin-shaped glossy green leaves. This Instagram-famous plant can grow up to 10 feet tall indoors, making it perfect for filling empty corners and adding a bold architectural element to your home decor.", "is_new": True},
        6: {"id": 6, "name": "ZZ Plant", "price": 24.00, "category": "indoor", "image": "indoor/ZZ_plants.jpg", "rating": 5, "description": "The ZZ Plant (Zamioculcas zamiifolia) is virtually indestructible with its glossy, waxy leaves and remarkable drought tolerance. This modern-looking plant thrives in low light and requires watering only once a month, making it perfect for offices or dark corners."},
        7: {"id": 7, "name": "Jade Plant", "price": 16.00, "category": "indoor", "image": "indoor/Jade Plant.jpg", "rating": 5, "description": "The Jade Plant is a beautiful succulent with thick, fleshy oval leaves that symbolize good luck and prosperity in many cultures. This easy-care plant develops a tree-like appearance over time and can live for decades with minimal care.", "is_popular": True},
        8: {"id": 8, "name": "Money Tree", "price": 28.00, "category": "indoor", "image": "indoor/money_tree.jpg", "rating": 4, "description": "The Money Tree (Pachira aquatica) features a distinctive braided trunk and palmate leaves, believed to bring good fortune and financial luck. This tropical plant prefers bright, indirect light and adds an elegant touch to any room with its unique architectural form."},
        9: {"id": 9, "name": "Lavender", "price": 15.00, "category": "outdoor", "image": "outdoor/lavender.jpg", "rating": 5, "description": "Fragrant lavender is a beautiful perennial herb with silvery-green foliage and iconic purple flower spikes. Known for its calming scent and therapeutic properties, lavender attracts beneficial pollinators while providing natural aromatherapy for your garden.", "is_popular": True},
        10: {"id": 10, "name": "Rosemary", "price": 12.00, "category": "outdoor", "image": "outdoor/rosemary.jpg", "rating": 4, "description": "Rosemary is an aromatic evergreen herb with needle-like leaves and a pine-like fragrance. This versatile Mediterranean plant is perfect for culinary use, producing small blue flowers while providing year-round greenery and natural pest deterrent properties."},
        11: {"id": 11, "name": "Sunflower", "price": 18.00, "category": "outdoor", "image": "outdoor/sunflower.jpg", "rating": 5, "description": "Bright and cheerful sunflowers are annual plants that follow the sun throughout the day, producing large golden blooms that can reach impressive heights. These happy flowers attract birds and beneficial insects while providing edible seeds.", "is_new": True},
        12: {"id": 12, "name": "Palm Tree", "price": 45.00, "category": "outdoor", "image": "outdoor/palm_tree.jpg", "rating": 4, "description": "This tropical palm brings exotic beauty to outdoor spaces with its fan-shaped or feathery fronds. Perfect for creating a resort-like atmosphere, palms are relatively low-maintenance once established and provide excellent shade and privacy screening."},
        13: {"id": 13, "name": "White Ceramic Pot", "price": 25.00, "category": "pot", "image": "pot/ceramic-pot-white.jpg", "rating": 4, "description": "This modern white ceramic pot features a clean, minimalist design that complements any plant and home decor style. Made from high-quality ceramic with a smooth glazed finish, it includes a drainage hole for healthy plant growth.", "is_popular": True},
        14: {"id": 14, "name": "Decorative Planter", "price": 32.00, "category": "pot", "image": "pot/Latitude_Run.jpg", "rating": 4, "description": "This elegant decorative planter features sophisticated styling perfect for modern homes. Made from durable materials with excellent craftsmanship, it's designed to showcase your favorite plants while adding aesthetic appeal to any space.", "is_new": True},
        15: {"id": 15, "name": "Garden Shears", "price": 24.00, "category": "accessories", "image": "accessories/Garden_Shears.jpg", "rating": 5, "description": "Professional-grade garden shears with sharp stainless steel blades and comfortable ergonomic handles. Perfect for pruning, deadheading, and harvesting, these precision tools make plant maintenance easy and efficient.", "is_popular": True},
        16: {"id": 16, "name": "Watering Can", "price": 35.00, "category": "accessories", "image": "accessories/Bloom_Pine_Watering_Can.jpg", "rating": 4, "description": "This elegant vintage-style watering can combines functionality with aesthetic appeal. Featuring a long spout for precise watering and comfortable handle, it's perfect for both indoor plants and small garden areas.", "is_on_sale": True},
        17: {"id": 17, "name": "Gardening Gloves", "price": 15.00, "category": "accessories", "image": "accessories/Gardening_Gloves.jpg", "rating": 4, "description": "Durable and comfortable gardening gloves that protect your hands while maintaining dexterity. Made with breathable materials and reinforced palms, these gloves are perfect for all gardening tasks from planting to pruning."},
        18: {"id": 18, "name": "Modern Planter Set", "price": 42.00, "category": "pot", "image": "pot/Stewart_Garden.jpg", "rating": 5, "description": "This contemporary planter set offers versatile styling for both indoor and outdoor use. Made from weather-resistant materials with excellent drainage, perfect for creating beautiful plant displays throughout your home and garden.", "is_new": True},
    }
    
    product = products.get(product_id)
    if not product:
        abort(404)
    
    # Convert dictionary to list for template filtering
    products_list = list(products.values())
    
    return render_template('shop/product_detail.html', title=f"Green Garden - {product['name']}", product=product, products=products_list)
